project:
  type: website
  output-dir: docs
  resources:
    - files/**
  preview:
    watch-inputs: true

execute:
  freeze: auto
  cache: true

website:
  site-url: https://ecocommonsaustralia.github.io/notebook-blog
  repo-url: https://github.com/EcoCommonsAustralia/notebook-blog
  favicon: images/favicon_square.png
  navbar:
    left:
      - href: index.qmd
        text: "<img src='https://raw.githubusercontent.com/EcoCommons-Australia-2024-2026/ec-notebook_site_materials/main/images/EcoCommons%20Logo%20White.png' alt='EcoCommons Logo' style='height:40px; vertical-align: middle; margin-right: 5px;'> <span style='font-size: 25px; position: relative; top: 7px;'>EcoNotebooks</span>"
      - href: https://github.com/EcoCommonsAustralia/notebooks
        text: "<img src='https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg' alt='GitHub' style='height:32px; vertical-align: middle; position: relative; top: 6px;'>"
    right:
      - text: Ecological and Spatial Tools
        menu:
          - href: notebooks/Rich_Div/richness_shannon_notebook.qmd
            text: Species Richness and Shannon Diversity
          - href: notebooks/sp/ecocommons-marxan-integration-poc.qmd
            text: Spatial Prioritization - Connecting Marxan
          - href: notebooks/raster_format.qmd
            text: Raster file format convert
          - href: notebooks/SpeciesNet/EC_run_speciesnet_on_WildObs_data.qmd
            text: Automated Wildlife Identification with SpeciesNet
      - text: Modelling Steps
        menu:
          - href: notebooks/dataprep.qmd
            text: Data Preparation
      - text: Ecological Models
        menu:
          - href: notebooks/EC_GLM/EC_GLM.qmd
            text: GLM with R     
          - href: notebooks/EC_RF/EC_RF.qmd
            text: Random Forest
          - href: notebooks/EOO_AOO/eoo_aoo.qmd
            text: Extent and Area of Ocurrence / Occupancy
          - href: notebooks/Occupancy_conceptual/EC_Occupancy_conceptual.qmd
            text: Single-Species Single-Season Occupancy Model - Conceptual
          - href: notebooks/Occupancy_practical/EC_Occupancy_practical.qmd
            text: Single-Species Single-Season Occupancy Model - Practical
      - href: notebooks/sdm_agreement/EC_sdm_agreement.qmd
        text: SDM Agreement Unit Tests
      - href: about.qmd
        text: About


format:
  html:
    css: styles/ec_html_template.css
    toc: true
    toc-depth: 5
    include-after-body: footer.html
    include-in-header: files/includes/_msclarity.html

editor: visual

