project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: "<img src='https://raw.githubusercontent.com/EcoCommons-Australia-2024-2026/ec-notebook_site_materials/main/images/EcoCommons%20Logo%20White.png' alt='EcoCommons Logo' style='height:40px; vertical-align: middle; margin-right: 5px;'> <span style='font-size: 25px; position: relative; top: 7px;'>EcoNotebooks</span>"
    right:
      - text: Ecological Analysis
        menu:
          - href: notebooks/Rich_Div/richness_shannon_notebook.qmd
            text: Species Richness and Shannon Diversity
      - text: Modelling Steps
        menu:
          - href: notebooks/dataprep.qmd
            text: Data Preparation
      - text: SDMs
        menu:
          - href: notebooks/EC_GLM/EC_GLM.qmd
            text: GLM
          - href: notebooks/EC_RF/EC_RF.qmd
            text: Random Forest
          - href: notebooks/EOO_AOO/eoo_aoo.qmd
            text: Extent and Area of Ocurrence / Occupancy
      - text: Spatial Prioritization
        menu:
          - href: notebooks/sp/ecocommons-marxan-integration-poc.qmd
            text: Connecting Marxan
      - href: about.qmd
        text: About

format:
  html:
    css: styles/ec_html_template.css
    toc: true
    include-after-body: footer.html

editor: visual

