---
title: "index"
format: html
editor: visual
---

# EcoCommons Notebooks

EcoCommons Notebooks represent an exciting expansion of the platform’s capabilities, offering a new layer of flexibility for advanced users. By incorporating notebooks, EcoCommons enhances its ability to serve the environmental data science community, enabling users to engage with cutting-edge methods, customize workflows, and increase reproducibility in their research. These notebooks, hosted on trusted cloud providers, provide a transparent, open-access approach to environmental data analysis while adhering to the FAIR principles. With planned monthly releases, EcoCommons Notebooks will empower users to explore complex topics such as species migration, community modeling, and data cleaning for biodiversity research.

# Publications used EcoCommons Platform

Bayraktarov, E., Low-Choy, S., Singh, A. R., Beaumont, L. J., Williams, K. J., Baumgartner, J. B., ... & Mackey, B. (2025). EcoCommons Australia virtual laboratories with cloud computing: Meeting diverse user needs for ecological modeling and decision-making. *Environmental Modelling & Software*, *183*, 106255.

Humaida, N., Wahab, L., Saputra, M. H., Kurniawati, F., Atmaja, M. B., Pujiono, E., ... & Wahyuningtyas, R. S. (2025). Species Distribution Model and Conservation of Mentaok (Wrightia javanica) in Indonesia. *Jurnal Manajemen Hutan Tropika*, *31*(1), 1-11.

Norman, Patrick, and Brendan Mackey. "A decision support tool for habitat connectivity in Australia." *Pacific Conservation Biology* 30, no. 5 (2024).

Isaza-Toro, Estefania, John Josephraj-Selvaraj, and Alan Giraldo. "Geographical distribution model of the fish Coryphaena hippurus (Perciformes: Coryphaenidae) according to climate change in the Pacific Oriental Tropical." *Revista de Biología Tropical* 72, no. 1 (2024).

Torkkola, Janne, Harry Hines, Alienor Chauvenet, and Paul Oliver. "Are species richness and endemism hotspots correlated within a biome? A test case in the fire-impacted subtropical rainforests of Australia." (2024).

Saputra, M. H., Humaida, N., & Hadiyan, Y. (2023). Smart farming: modeling distribution of Xanthomonas campestris pv. oryzae as a leaf blight-causing bacteria in rice plants. In *IOP Conference Series: Earth and Environmental Science* (Vol. 1133, No. 1, p. 012026). IOP Publishing.

Saputra, M. H., & Humaida, N. (2023, June). Potential future distribution of Scirpophaga incertulas (Walker) in Indonesia. In *IOP Conference Series: Earth and Environmental Science* (Vol. 1182, No. 1, p. 012007). IOP Publishing.

Levett, Kerry, Jonathan Smillie, and Andrew Treloar. "Putting the R into PlatfoRms." *International Journal of Digital Curation* 17, no. 1 (2023): 12-12.
