<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Cross-validating EcoCommons SDM outputs against reference implementations — a dashboard of the scientific-agreement unit tests that guard every species distribution model algorithm on the EcoCommons platform.">

<title>ec_sdm_agreement</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon_square.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-79108a0fc1995748cbd19a5b0e3e3e7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "utga310w5s");
</script>


<link rel="stylesheet" href="../../styles/ec_html_template.css">
</head>

<body class="fullcontent nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text"><img src="https://raw.githubusercontent.com/EcoCommons-Australia-2024-2026/ec-notebook_site_materials/main/images/EcoCommons%20Logo%20White.png" alt="EcoCommons Logo" style="height:40px; vertical-align: middle; margin-right: 5px;"> <span style="font-size: 25px; position: relative; top: 7px;">EcoNotebooks</span></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/EcoCommonsAustralia/notebooks"> 
<span class="menu-text"><img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg" alt="GitHub" style="height:32px; vertical-align: middle; position: relative; top: 6px;"></span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ecological-and-spatial-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Ecological and Spatial Tools</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-ecological-and-spatial-tools">    
        <li>
    <a class="dropdown-item" href="../../notebooks/Rich_Div/richness_shannon_notebook.html">
 <span class="dropdown-text">Species Richness and Shannon Diversity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/sp/ecocommons-marxan-integration-poc.html">
 <span class="dropdown-text">Spatial Prioritization - Connecting Marxan</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/raster_format.html">
 <span class="dropdown-text">Raster file format convert</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/SpeciesNet/EC_run_speciesnet_on_WildObs_data.html">
 <span class="dropdown-text">Automated Wildlife Identification with SpeciesNet</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-modelling-steps" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Modelling Steps</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-modelling-steps">    
        <li>
    <a class="dropdown-item" href="../../notebooks/dataprep.html">
 <span class="dropdown-text">Data Preparation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ecological-models" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Ecological Models</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-ecological-models">    
        <li>
    <a class="dropdown-item" href="../../notebooks/EC_GLM/EC_GLM.html">
 <span class="dropdown-text">GLM with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/EC_RF/EC_RF.html">
 <span class="dropdown-text">Random Forest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/EOO_AOO/eoo_aoo.html">
 <span class="dropdown-text">Extent and Area of Ocurrence / Occupancy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/Occupancy_conceptual/EC_Occupancy_conceptual.html">
 <span class="dropdown-text">Single-Species Single-Season Occupancy Model - Conceptual</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../notebooks/Occupancy_practical/EC_Occupancy_practical.html">
 <span class="dropdown-text">Single-Species Single-Season Occupancy Model - Practical</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="../../notebooks/sdm_agreement/EC_sdm_agreement.html" aria-current="page"> 
<span class="menu-text">SDM Agreement Unit Tests</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#cross-validating-ecocommons-sdm-outputs-against-reference-implementations-on-development" id="toc-cross-validating-ecocommons-sdm-outputs-against-reference-implementations-on-development" class="nav-link active" data-scroll-target="#cross-validating-ecocommons-sdm-outputs-against-reference-implementations-on-development">Cross-validating EcoCommons SDM outputs against reference implementations (on development)</a></li>
  <li><a href="#script-information" id="toc-script-information" class="nav-link" data-scroll-target="#script-information">Script information</a>
  <ul>
  <li><a href="#algorithm-coverage" id="toc-algorithm-coverage" class="nav-link" data-scroll-target="#algorithm-coverage">Algorithm coverage</a></li>
  <li><a href="#overview-all-tests-grouped-by-model-family" id="toc-overview-all-tests-grouped-by-model-family" class="nav-link" data-scroll-target="#overview-all-tests-grouped-by-model-family">Overview — all tests, grouped by model family</a></li>
  <li><a href="#model-configurations-nsw14-suite" id="toc-model-configurations-nsw14-suite" class="nav-link" data-scroll-target="#model-configurations-nsw14-suite">Model configurations (nsw14 suite)</a>
  <ul>
  <li><a href="#benchmark-references" id="toc-benchmark-references" class="nav-link" data-scroll-target="#benchmark-references">Benchmark references</a></li>
  </ul></li>
  <li><a href="#geographic-spatial-only-models" id="toc-geographic-spatial-only-models" class="nav-link" data-scroll-target="#geographic-spatial-only-models">Geographic (spatial-only) models</a>
  <ul>
  <li><a href="#two-references-both-checked" id="toc-two-references-both-checked" class="nav-link" data-scroll-target="#two-references-both-checked">Two references, both checked</a></li>
  </ul></li>
  <li><a href="#prediction-maps" id="toc-prediction-maps" class="nav-link" data-scroll-target="#prediction-maps">Prediction maps</a>
  <ul>
  <li><a href="#single-species-benchmark-predictions" id="toc-single-species-benchmark-predictions" class="nav-link" data-scroll-target="#single-species-benchmark-predictions">Single-species benchmark predictions</a></li>
  <li><a href="#nsw14-valavi-continuous-surface-published-points-agreement" id="toc-nsw14-valavi-continuous-surface-published-points-agreement" class="nav-link" data-scroll-target="#nsw14-valavi-continuous-surface-published-points-agreement">nsw14 (Valavi) — continuous surface, published points &amp; agreement</a></li>
  </ul></li>
  <li><a href="#agreement-analysis" id="toc-agreement-analysis" class="nav-link" data-scroll-target="#agreement-analysis">Agreement analysis</a>
  <ul>
  <li><a href="#ecocommons-vs-benchmark-every-test" id="toc-ecocommons-vs-benchmark-every-test" class="nav-link" data-scroll-target="#ecocommons-vs-benchmark-every-test">EcoCommons vs benchmark — every test</a></li>
  </ul></li>
  <li><a href="#reproducibility-benchmark-provenance" id="toc-reproducibility-benchmark-provenance" class="nav-link" data-scroll-target="#reproducibility-benchmark-provenance">Reproducibility &amp; benchmark provenance</a>
  <ul>
  <li><a href="#two-different-reference-points" id="toc-two-different-reference-points" class="nav-link" data-scroll-target="#two-different-reference-points">Two different reference points</a></li>
  <li><a href="#what-changes-the-final-benchmark" id="toc-what-changes-the-final-benchmark" class="nav-link" data-scroll-target="#what-changes-the-final-benchmark">What changes the final benchmark</a></li>
  <li><a href="#why-regenerating-in-the-same-environment-is-safe" id="toc-why-regenerating-in-the-same-environment-is-safe" class="nav-link" data-scroll-target="#why-regenerating-in-the-same-environment-is-safe">Why regenerating in the same environment is safe</a></li>
  <li><a href="#reproducibility-environment-pinned-package-versions" id="toc-reproducibility-environment-pinned-package-versions" class="nav-link" data-scroll-target="#reproducibility-environment-pinned-package-versions">Reproducibility environment — pinned package versions</a></li>
  </ul></li>
  <li><a href="#crossr-version-reproducibility-the-four-not-yet-tested-biomod2-learners-sre-fda-ann-gbm" id="toc-crossr-version-reproducibility-the-four-not-yet-tested-biomod2-learners-sre-fda-ann-gbm" class="nav-link" data-scroll-target="#crossr-version-reproducibility-the-four-not-yet-tested-biomod2-learners-sre-fda-ann-gbm">Cross–R-version reproducibility: the four “not-yet-tested” <code>biomod2</code> learners (SRE · FDA · ANN · GBM)</a></li>
  <li><a href="#methods-metrics-for-reproduction-performance" id="toc-methods-metrics-for-reproduction-performance" class="nav-link" data-scroll-target="#methods-metrics-for-reproduction-performance">Methods — metrics for reproduction performance</a>
  <ul>
  <li><a href="#two-metrics" id="toc-two-metrics" class="nav-link" data-scroll-target="#two-metrics">Two metrics</a></li>
  <li><a href="#reading-the-agreement-scatter" id="toc-reading-the-agreement-scatter" class="nav-link" data-scroll-target="#reading-the-agreement-scatter">Reading the agreement scatter</a></li>
  <li><a href="#deterministic-vs-stochastic-learners" id="toc-deterministic-vs-stochastic-learners" class="nav-link" data-scroll-target="#deterministic-vs-stochastic-learners">Deterministic vs stochastic learners</a></li>
  </ul></li>
  <li><a href="#ecocommons-agreement-on-the-hsdm-data-sre-fda-ann-gbm" id="toc-ecocommons-agreement-on-the-hsdm-data-sre-fda-ann-gbm" class="nav-link" data-scroll-target="#ecocommons-agreement-on-the-hsdm-data-sre-fda-ann-gbm">EcoCommons agreement on the HSDM data (SRE · FDA · ANN · GBM)</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<p><img src="https://raw.githubusercontent.com/EcoCommons-Australia-2024-2026/ec-notebook_site/main/images/notebooks_banner_withframe.png" class="img-fluid"></p>
<section id="cross-validating-ecocommons-sdm-outputs-against-reference-implementations-on-development" class="level1">
<h1>Cross-validating EcoCommons SDM outputs against reference implementations (on development)</h1>
<p>Author details: Xiang Zhao</p>
<p>Contact details: support@ecocommons.org.au</p>
<p>Copyright statement: This script is the product of the EcoCommons platform. Please refer to the EcoCommons website for more details: https://www.ecocommons.org.au/</p>
<p>Updated date: 25 August 2026</p>
</section>
<section id="script-information" class="level1">
<h1>Script information</h1>
<p>This page documents the scientific-agreement unit tests that guard every species distribution model (SDM) algorithm on the EcoCommons platform. Each test runs a real EcoCommons projection and compares it against an independent reference implementation — the algorithm’s own R package, Valavi et al.&nbsp;(2021)’s published benchmark on the NCEAS <code>nsw14</code> data, the reference implementations in Hijmans &amp; Elith’s <em>Species distribution modeling with R</em> (the <code>dismo</code> vignette), or our verbatim reproduction of Guisan, Thuiller &amp; Zimmermann’s <em>Habitat Suitability and Distribution Models</em> (2017) on the <em>Vulpes vulpes</em> data (for SRE, FDA, ANN and GBM).</p>
<p>Every SDM agreement test in the EcoCommons R package (<code>tests/testthat/test-sdm_projection_agreement.R</code>) runs a real EcoCommons projection and compares it to a reference benchmark — the algorithm’s own R package, Valavi et al.&nbsp;(2021)’s published benchmark on the NCEAS <code>nsw14</code> data, or our HSDM (Guisan et al.&nbsp;2017) <em>Vulpes vulpes</em> reproduction.</p>
<section id="algorithm-coverage" class="level2">
<h2 class="anchored" data-anchor-id="algorithm-coverage">Algorithm coverage</h2>
<p>EcoCommons ships <strong>19 species-distribution / geographic algorithms</strong>. <strong>16 are guarded by a scientific-agreement unit test (SRE, FDA, ANN and GBM newly added against the HSDM <em>Vulpes vulpes</em> reproduction — ANN as a 50× ensemble, a deliberate change from the book’s single fit); 3 are not yet covered.</strong></p>
<table class="table table-sm caption-top" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Algorithm</th>
<th data-quarto-table-cell-role="th">EcoCommons engine</th>
<th data-quarto-table-cell-role="th">Sci Unit Test?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="9" style="vertical-align: middle"><code>biomod2</code> SDMs</td>
<td>GLM</td>
<td><code>stats::glm</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>GAM</td>
<td><code>mgcv::gam</code></td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td>RF</td>
<td><code>randomForest</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>MARS</td>
<td><code>earth</code></td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td>GBM</td>
<td><code>gbm</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>CTA</td>
<td><code>rpart</code></td>
<td>❌ not yet</td>
</tr>
<tr class="odd">
<td>FDA</td>
<td><code>mda</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>ANN</td>
<td><code>nnet</code></td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td>SRE</td>
<td><code>biomod2</code> (envelope)</td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td rowspan="3" style="vertical-align: middle"><code>dismo</code> SDMs</td>
<td>MaxEnt</td>
<td>maxent.jar</td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td>BRT</td>
<td><code>dismo::gbm.step</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>Bioclim</td>
<td><code>dismo::bioclim</code></td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td rowspan="5" style="vertical-align: middle">Geographic<br>
(spatial-only)</td>
<td>GeoDist</td>
<td><code>dismo::geoDist</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>Convex Hull</td>
<td><code>dismo::convHull</code></td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td>Circles</td>
<td><code>dismo::circles</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td>GeoIDW</td>
<td><code>dismo::geoIDW</code></td>
<td>✅ tested</td>
</tr>
<tr class="odd">
<td>Voronoi Hull</td>
<td><code>dismo::voronoiHull</code></td>
<td>✅ tested</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Niche / match</td>
<td>Range bagging</td>
<td><code>ecospat</code>-style range bagging</td>
<td>❌ not yet</td>
</tr>
<tr class="odd">
<td>Climatch</td>
<td>climate-matching</td>
<td>❌ not yet</td>
</tr>
</tbody>
</table>
<p><strong>Sci-unit-tested (16):</strong> GLM, GAM, RF, MARS, MaxEnt, BRT, Bioclim, GeoDist, Convex Hull, Circles, GeoIDW, Voronoi Hull, SRE, FDA, ANN, and GBM. <strong>Not yet covered (3):</strong> CTA, Range bagging, Climatch. <em>(The <code>speciestrait_*</code> / <code>traitdiff_*</code> trait-difference functions are out of scope here — they are not species-distribution models.)</em></p>
</section>
<section id="overview-all-tests-grouped-by-model-family" class="level2">
<h2 class="anchored" data-anchor-id="overview-all-tests-grouped-by-model-family">Overview — all tests, grouped by model family</h2>
<p>Every test runs a real EcoCommons projection and scores it against a reference implementation on <strong>Pearson</strong> correlation of predicted suitability. Rows are grouped by algorithm family (Profile · Machine Learning · Statistical · Geographic); the three algorithms not yet covered (Climatch-lite, Range Bagging, CTA) are shown in their family for completeness.</p>
<table class="table table-sm caption-top" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">#</th>
<th data-quarto-table-cell-role="th">Algorithm</th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">EcoCommons engine</th>
<th data-quarto-table-cell-role="th">Reference benchmark</th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Threshold</th>
<th data-quarto-table-cell-role="th">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td colspan="8" style="background: #eef0f6; font-weight: 700">Profile Models</td>
</tr>
<tr class="even">
<td>1</td>
<td style="font-weight: 600">BIOCLIM</td>
<td><em>Bradypus variegatus</em></td>
<td><code>dismo::bioclim</code></td>
<td>dismo bioclim</td>
<td>Pearson</td>
<td>0.90</td>
<td><strong>0.980</strong> ✓</td>
</tr>
<tr class="odd">
<td>—</td>
<td style="font-weight: 600">Climatch-lite</td>
<td>—</td>
<td>climate-matching</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>❌ not yet</td>
</tr>
<tr class="even">
<td>—</td>
<td style="font-weight: 600">Range Bagging</td>
<td>—</td>
<td><code>ecospat</code>-style range bagging</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>❌ not yet</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="font-weight: 600">Surface Range Envelope (SRE)</td>
<td><em>Vulpes vulpes</em></td>
<td>biomod2 <code>bm_SRE</code></td>
<td>HSDM (Guisan et al. 2017) reproduction</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="even">
<td colspan="8" style="background: #eef0f6; font-weight: 700">Machine Learning Models</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="font-weight: 600">Artificial Neural Network (ANN)</td>
<td><em>Vulpes vulpes</em></td>
<td>biomod2 <code>nnet</code> <em>(50× ensemble)</em></td>
<td>HSDM reproduction <em>(50× ensemble)</em></td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>0.996</strong> ✓</td>
</tr>
<tr class="even">
<td>4</td>
<td rowspan="2" style="vertical-align: middle; font-weight: 600">Boosted Regression Tree (BRT)</td>
<td><em>Anguilla australis</em></td>
<td><code>dismo::gbm.step</code> (unit weights)</td>
<td>dismo gbm.step (unit weights)</td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>0.985</strong> ✓</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>nsw14</code></td>
<td><code>dismo::gbm.step</code> <em>(test mocks down-weighting)</em></td>
<td>gbm.step (down-weighted)</td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="even">
<td>—</td>
<td style="font-weight: 600">Classification Tree (CTA)</td>
<td>—</td>
<td><code>rpart</code></td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>❌ not yet</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="font-weight: 600">Generalized Boosting Model (GBM)</td>
<td><em>Vulpes vulpes</em></td>
<td>biomod2 <code>gbm</code> <em>(book config)</em></td>
<td>HSDM reproduction</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>0.999</strong> ✓</td>
</tr>
<tr class="even">
<td>7</td>
<td rowspan="2" style="vertical-align: middle; font-weight: 600">Maxent</td>
<td><em>Bradypus variegatus</em></td>
<td>maxent.jar</td>
<td>maxent.jar <code>_avg</code></td>
<td>Pearson</td>
<td>0.90</td>
<td><strong>0.987</strong> ✓</td>
</tr>
<tr class="odd">
<td>8</td>
<td><code>nsw14</code></td>
<td>maxent.jar</td>
<td><code>dismo::maxent</code></td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>0.989</strong> ✓</td>
</tr>
<tr class="even">
<td>9</td>
<td rowspan="2" style="vertical-align: middle; font-weight: 600">Random Forest (RF)</td>
<td><em>Bradypus variegatus</em></td>
<td>biomod2 RF</td>
<td>biomod2 RF</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>0.998</strong> ✓</td>
</tr>
<tr class="odd">
<td>10</td>
<td><code>nsw14</code></td>
<td>biomod2 RF <em>(rescale off)</em></td>
<td><code>randomForest</code></td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>0.986</strong> ✓</td>
</tr>
<tr class="even">
<td colspan="8" style="background: #eef0f6; font-weight: 700">Statistical Models</td>
</tr>
<tr class="odd">
<td>11</td>
<td style="font-weight: 600">Flexible Discriminant Analysis (FDA)</td>
<td><em>Vulpes vulpes</em></td>
<td>biomod2 <code>mda</code> (MARS)</td>
<td>HSDM reproduction</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>0.999</strong> ✓</td>
</tr>
<tr class="even">
<td>12</td>
<td style="font-weight: 600">Generalized Additive Model (GAM)</td>
<td><code>nsw14</code></td>
<td>biomod2 <code>GAM_mgcv</code> <em>(rescale off)</em></td>
<td><code>mgcv::gam</code> (all-smoothed, presence up-weighted)</td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="odd">
<td>13</td>
<td rowspan="2" style="vertical-align: middle; font-weight: 600">Generalized Linear Model (GLM)</td>
<td><em>Bradypus variegatus</em></td>
<td>biomod2 GLM</td>
<td>biomod2 GLM</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="even">
<td>14</td>
<td><code>nsw14</code> (NSW bird)</td>
<td>biomod2 GLM <em>(rescale off)</em></td>
<td><code>gam::step.Gam</code></td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>0.975</strong> ✓</td>
</tr>
<tr class="odd">
<td>15</td>
<td style="font-weight: 600">Multivariate Adaptive Regression Splines (MARS)</td>
<td><code>nsw14</code></td>
<td>biomod2 <code>earth</code> <em>(rescale off)</em></td>
<td><code>earth</code> (glm=binomial, down-weighted)</td>
<td>Pearson</td>
<td>0.95</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="even">
<td colspan="8" style="background: #eef0f6; font-weight: 700">Geographic Models</td>
</tr>
<tr class="odd">
<td>16</td>
<td style="font-weight: 600">Circles</td>
<td><em>Bradypus variegatus</em></td>
<td><code>dismo::circles</code></td>
<td>dismo circles</td>
<td>Presence footprint</td>
<td>—</td>
<td><strong>identical</strong> ✓</td>
</tr>
<tr class="even">
<td>17</td>
<td style="font-weight: 600">Convex Hull</td>
<td><em>Bradypus variegatus</em></td>
<td><code>dismo::convHull</code></td>
<td>dismo convHull</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>1.000</strong> ✓ <em>(TSS 1.000)</em></td>
</tr>
<tr class="odd">
<td>18</td>
<td style="font-weight: 600">Geographic Distance (GeoDist)</td>
<td><em>Bradypus variegatus</em></td>
<td><code>dismo::geoDist</code></td>
<td>dismo geoDist (book config)</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="even">
<td>19</td>
<td style="font-weight: 600">Inverse-Distance Weighted (GeoIDW)</td>
<td><em>Bradypus variegatus</em></td>
<td><code>dismo::geoIDW</code></td>
<td>dismo geoIDW</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>1.000</strong> ✓</td>
</tr>
<tr class="odd">
<td>20</td>
<td style="font-weight: 600">Voronoi Hull</td>
<td><em>Bradypus variegatus</em></td>
<td><code>dismo::voronoiHull</code></td>
<td>dismo voronoiHull</td>
<td>Pearson</td>
<td>0.99</td>
<td><strong>1.000</strong> ✓</td>
</tr>
</tbody>
</table>
<p><strong>All 20 pass — geoDist/convHull/geoIDW/voronoiHull reproduce the reference to Pearson 1.000, and Circles reproduces the reference presence footprint exactly once a two-part bug is fixed (see the geographic-models section below).</strong></p>
<p>Rows 12–16 are the <strong>geographic (spatial-only) models</strong> — they predict from the geographic location of occurrences, not from environmental predictors — so their reference is the algorithm’s own <code>dismo</code> function as taught in Hijmans &amp; Elith’s <em>Species distribution modeling with R</em> (Chapter 13).</p>
<p><strong>Calibration alignment</strong> — every EcoCommons↔︎reference gap turned out to be <strong>weighting or rescaling, never the underlying learner</strong>:</p>
<ul>
<li><strong>RF, GLM</strong> — <code>rescale_all_models = false</code>: RF Pearson <strong>0.89 → 0.99</strong>, GLM <strong>0.96 → 0.98</strong>.</li>
<li><strong>MARS</strong> — biomod2 fits <code>earth(glm=binomial, weights=prevalence)</code>; the benchmark uses the same background down-weighting: <strong>0.72 → 1.00</strong>. (Earlier thought to be an unfixable wrapper difference — it was just the missing weights.)</li>
<li><strong>GAM</strong> — biomod2 <code>GAM_mgcv</code> applies prevalence=0.5 as <strong>presence up-weighting</strong> (presence weight = bgNum/prNum, background = 1). For a GAM under UBRE the <em>absolute</em> weight scale drives smoothing-parameter selection, so Valavi’s background <em>down</em>-weighting (same ratio, ~60× smaller total) selects different smoothness: <strong>0.87 → 1.00</strong> once the benchmark matches biomod2’s presence up-weighting (both engines are <code>mgcv</code>).</li>
<li><strong>BRT</strong> — Valavi down-weights the background; EcoCommons <strong>production uses unit weights</strong> (down-weighting is <em>proposed, not applied</em>). The nsw14 BRT test <strong>mocks</strong> the internal weighting to down-weight — matching Valavi’s config (Pearson <strong>1.000</strong>) — while the Anguilla BRT test keeps exercising the real unit-weight path (0.985).</li>
</ul>
<p>Species: <em>Bradypus variegatus</em> (three-toed sloth, South America); <em>Anguilla australis</em> (short-finned eel, NZ); <code>nsw14</code> (anonymised NSW diurnal bird, Valavi/NCEAS).</p>
</section>
<section id="model-configurations-nsw14-suite" class="level2">
<h2 class="anchored" data-anchor-id="model-configurations-nsw14-suite">Model configurations (nsw14 suite)</h2>
<p><strong>Shared setup:</strong> species <code>nsw14</code> (315 presences from <code>disPo</code> + background), 11 continuous NSW predictors (<code>cti, disturb, mi, rainann, raindq, rugged, soildepth, soilfert, solrad, tempann, topo</code>), <code>random_seed = 0</code>, deduplicated to one record per raster cell (8190 points).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th>EcoCommons (test config)</th>
<th>Valavi reference (benchmark)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GLM</strong></td>
<td>biomod2 GLM — <code>type=quadratic</code>, <code>test=AIC</code> (stepwise both directions), <code>family=binomial</code>, <strong><code>rescale_all_models=false</code></strong></td>
<td><code>glm</code> → <code>gam::step.Gam</code> — per-var scope {drop / linear / <code>poly(,2)</code>}, AIC both directions, background down-weighted, normalised</td>
</tr>
<tr class="even">
<td><strong>GAM</strong></td>
<td>biomod2 <code>GAM_mgcv</code> — <code>s_smoother</code> on all 11 predictors, <code>k=-1</code>, <code>method=GCV.Cp</code>, <strong>presence up-weighted</strong>, <strong><code>rescale_all_models=false</code></strong></td>
<td><code>mgcv::gam</code> — <code>s()</code> on all predictors, <code>method=GCV.Cp</code>, presence up-weighted (matched to biomod2)</td>
</tr>
<tr class="odd">
<td><strong>MaxEnt</strong></td>
<td>maxent.jar — autofeature (L+Q+P+H), <code>betamultiplier=1</code>, <code>maximumiterations=500</code>, cloglog</td>
<td><code>dismo::maxent</code> (maxent.jar) — <code>args="nothreshold"</code>, cloglog, not normalised</td>
</tr>
<tr class="even">
<td><strong>RF</strong></td>
<td>biomod2 RF — classification, <code>ntree=500</code>, <code>mtry=default</code>, <code>nodesize=5</code>, <strong><code>rescale_all_models=false</code></strong></td>
<td><code>randomForest</code> — classification, <code>ntree=500</code>, <code>type="prob"</code></td>
</tr>
<tr class="odd">
<td><strong>MARS</strong></td>
<td>biomod2 <code>earth</code> — <code>type=simple</code> (degree 1), <code>penalty=2</code>, <code>thresh=0.001</code>, <code>pmethod=backward</code>, <code>glm=binomial</code>, prevalence-weighted, <strong><code>rescale_all_models=false</code></strong></td>
<td><code>earth</code> — <code>degree=1</code>, <code>pmethod=backward</code>, <code>glm=binomial</code>, background down-weighted (matched to biomod2)</td>
</tr>
<tr class="even">
<td><strong>BRT</strong></td>
<td><code>dismo::gbm.step</code> — <code>tree.complexity=5</code>, <code>learning.rate=0.001</code>, <code>bag.fraction=0.75</code>, <code>n.folds=5</code>, <code>n.trees=50</code>, <code>max.trees=10000</code>, <code>family=bernoulli</code>, <strong>unit weights (test mocks down-weighting)</strong></td>
<td><code>dismo::gbm.step</code> — same hyper-parameters, background down-weighted, normalised</td>
</tr>
</tbody>
</table>
<p><em>Bold = the calibration settings that were aligned. BRT uses Valavi’s exact hyper-parameters; the test mocks background down-weighting so it reproduces Valavi (<code>best.trees</code> 4350 = 4350) without changing EcoCommons’ shipped unit-weight default. GLM is the only algorithm that can’t be config-matched — biomod2 GLM and <code>gam::step.Gam</code> are different engines.</em></p>
<p><em>The <strong>continuous suitability maps</strong> further below use Valavi’s <strong>original Appendix S2</strong> configs (e.g.&nbsp;MARS = caret-tuned <code>earth</code>, <code>nprune</code> 2–20; GAM = <code>mgcv::gam</code> REML with Valavi’s smooth / parametric split) — that’s why they reproduce Valavi’s published CSV points, whereas the benchmarks here are tuned to match EcoCommons (GAM: all-smoothed, <code>GCV.Cp</code>, presence up-weighted).</em></p>
<section id="benchmark-references" class="level3">
<h3 class="anchored" data-anchor-id="benchmark-references">Benchmark references</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Benchmark</th>
<th>Method paper</th>
<th>Engine / tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GLM</strong></td>
<td>McCullagh &amp; Nelder (1989); Hastie &amp; Tibshirani (1990) <code>step.Gam</code></td>
<td>biomod2 GLM (EC) / <code>gam::step.Gam</code> (Valavi)</td>
</tr>
<tr class="even">
<td><strong>GAM</strong></td>
<td>Hastie &amp; Tibshirani (1990); Wood (2017) <code>mgcv</code></td>
<td>biomod2 <code>GAM_mgcv</code> (EC) / <code>mgcv::gam</code> (Valavi)</td>
</tr>
<tr class="odd">
<td><strong>MaxEnt</strong></td>
<td>Phillips, Anderson &amp; Schapire (2006); Phillips &amp; Dudík (2008)</td>
<td>maxent.jar via <code>dismo</code></td>
</tr>
<tr class="even">
<td><strong>RF</strong></td>
<td>Breiman (2001)</td>
<td><code>randomForest</code></td>
</tr>
<tr class="odd">
<td><strong>MARS</strong></td>
<td>Friedman (1991)</td>
<td><code>earth</code></td>
</tr>
<tr class="even">
<td><strong>BRT</strong></td>
<td>Elith, Leathwick &amp; Hastie (2008)</td>
<td><code>dismo::gbm.step</code></td>
</tr>
<tr class="odd">
<td><strong>Bioclim</strong></td>
<td>Nix (1986); Booth et al.&nbsp;(2014)</td>
<td><code>dismo::bioclim</code></td>
</tr>
<tr class="even">
<td><strong>Geographic models</strong> (GeoDist, Convex Hull, Circles, GeoIDW, Voronoi Hull)</td>
<td>Hijmans &amp; Elith, <em>Species distribution modeling with R</em> (Ch. 13)</td>
<td><code>dismo::geoDist</code> / <code>convHull</code> / <code>circles</code> / <code>geoIDW</code> / <code>voronoiHull</code></td>
</tr>
<tr class="odd">
<td><strong>Background down-weighting</strong></td>
<td>Elith et al.&nbsp;(2008); Valavi et al.&nbsp;(2021)</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>nsw14 species + rasters (NCEAS)</strong></td>
<td>Elith et al.&nbsp;(2020)</td>
<td><code>disdat</code> / OSF <code>kwc4v</code></td>
</tr>
<tr class="odd">
<td><strong>Valavi reference configs</strong></td>
<td>Valavi et al.&nbsp;(2021)</td>
<td>Appendix S2</td>
</tr>
<tr class="even">
<td><strong>EcoCommons SDM platform</strong></td>
<td>Thuiller et al.&nbsp;(2009) <code>biomod2</code>; Hijmans et al.&nbsp;<code>dismo</code></td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="geographic-spatial-only-models" class="level2">
<h2 class="anchored" data-anchor-id="geographic-spatial-only-models">Geographic (spatial-only) models</h2>
<p>Rows 12–16 cover the five <strong>geographic models</strong> from Chapter 13 of Hijmans &amp; Elith’s <em>Species distribution modeling with R</em> (the <code>dismo</code> vignette). Unlike every other algorithm on this page, these predict a species purely from the <strong>geographic location</strong> of its occurrence records — distance to, or containment by, the known points — and ignore the environmental predictors entirely. EcoCommons wraps each one directly from <code>dismo</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th>EcoCommons function</th>
<th><code>dismo</code> engine</th>
<th>Uses absence?</th>
<th>Output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GeoDist</strong></td>
<td><code>EC_modelling_geodist</code></td>
<td><code>dismo::geoDist</code></td>
<td>no (presence-only)</td>
<td>continuous — inverse distance to nearest presence</td>
</tr>
<tr class="even">
<td><strong>Convex Hull</strong></td>
<td><code>EC_modelling_convhull</code></td>
<td><code>dismo::convHull</code></td>
<td>no</td>
<td>binary — inside/outside the presence hull</td>
</tr>
<tr class="odd">
<td><strong>Circles</strong></td>
<td><code>EC_modelling_circles</code></td>
<td><code>dismo::circles</code></td>
<td>no</td>
<td>binary — inside/outside circles around presences</td>
</tr>
<tr class="even">
<td><strong>GeoIDW</strong></td>
<td><code>EC_modelling_geoidw</code></td>
<td><code>dismo::geoIDW</code></td>
<td>yes (pres/abs)</td>
<td>continuous — inverse-distance-weighted interpolation</td>
</tr>
<tr class="odd">
<td><strong>Voronoi Hull</strong></td>
<td><code>EC_modelling_voronoihull</code></td>
<td><code>dismo::voronoiHull</code></td>
<td>yes</td>
<td>binary — Voronoi/Thiessen polygon classification</td>
</tr>
</tbody>
</table>
<section id="two-references-both-checked" class="level3">
<h3 class="anchored" data-anchor-id="two-references-both-checked">Two references, both checked</h3>
<p>Like the <code>nsw14</code> suite, these tests have two distinct reference points:</p>
<p><strong>1. Literature anchor — the textbook’s own reported numbers.</strong> Chapter 13 prints a <code>ModelEvaluation</code> (AUC, point-biserial cor) for each model on the <em>Bradypus variegatus</em> data. We reproduce those <strong>exactly, to seven decimals</strong>. Two things are required to hit them: (a) <code>RNGkind(sample.kind = "Rounding")</code> — the book predates R 3.6.0’s change to the <code>sample()</code> algorithm; and (b) replaying the book’s exact random-number stream (including two incidental <code>rnorm(50)</code> calls in its <code>evaluate()</code> demo) so the train/background splits match.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Book AUC</th>
<th>Reproduced AUC</th>
<th>Book cor</th>
<th>Reproduced cor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GeoDist</td>
<td>0.9006522</td>
<td><strong>0.9006522</strong></td>
<td>0.4197574</td>
<td><strong>0.4197574</strong></td>
</tr>
<tr class="even">
<td>Convex Hull</td>
<td>0.7490217</td>
<td><strong>0.7490217</strong></td>
<td>0.3036379</td>
<td><strong>0.3036379</strong></td>
</tr>
<tr class="odd">
<td>Circles</td>
<td>0.8547826</td>
<td><strong>0.8547826</strong></td>
<td>0.5103540</td>
<td><strong>0.5103540</strong></td>
</tr>
<tr class="even">
<td>GeoIDW</td>
<td>0.8893478</td>
<td><strong>0.8893478</strong></td>
<td>0.5354838</td>
<td><strong>0.5354838</strong></td>
</tr>
<tr class="odd">
<td>Voronoi Hull</td>
<td>0.5</td>
<td><strong>0.5</strong></td>
<td>NA</td>
<td><em>degenerate</em></td>
</tr>
</tbody>
</table>
<p><em>Voronoi Hull is reported by the book as a <strong>degenerate</strong> result (AUC exactly 0.5): it subsamples 100 background points at the very end of the vignette’s global RNG stream, and the resulting classification does not discriminate. We reproduce the same degeneracy.</em></p>
<p><strong>2. Implementation fidelity — EcoCommons vs an independent <code>dismo</code> run on identical inputs.</strong> This is the actual unit test (rows 12–16): run the real EcoCommons pipeline and, separately, call the same <code>dismo</code> function on the <em>same</em> occurrence / pseudo-absence set the platform used, then compare the prediction rasters.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>EcoCommons ↔︎ <code>dismo</code></th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GeoDist</td>
<td><strong>Pearson 1.0000</strong></td>
<td>identical surface (RMSE 0)</td>
</tr>
<tr class="even">
<td>Convex Hull</td>
<td><strong>Pearson 1.0000</strong></td>
<td>binary — TSS 1.000</td>
</tr>
<tr class="odd">
<td>GeoIDW</td>
<td><strong>Pearson 1.0000</strong></td>
<td>identical (RMSE 0)</td>
</tr>
<tr class="even">
<td>Voronoi Hull</td>
<td><strong>Pearson 1.0000</strong></td>
<td>identical (RMSE 0)</td>
</tr>
<tr class="odd">
<td>Circles</td>
<td><em>footprint identical</em></td>
<td>binary — presence inside circles</td>
</tr>
</tbody>
</table>
<p>Four of the five are <strong>implementation-identical</strong> — EcoCommons is a thin, faithful wrapper over the <code>dismo</code> engine, exactly as intended.</p>
<p><img src="images/geo_models_ec_vs_benchmark.png" class="img-fluid"></p>
<p><em>Each row is one geographic model, <code>dismo</code> reference (left) vs the EcoCommons projection (right), over the </em>Bradypus variegatus* range; white points are the occurrence records the model was fitted on. Continuous models (GeoDist, GeoIDW) use a percentile colour stretch; binary models (Convex Hull, Circles, Voronoi Hull) show presence (green) vs absence (grey). For every model the two columns are visually indistinguishable — GeoDist, Convex Hull, GeoIDW and Voronoi Hull agree at Pearson r = 1.000, and Circles reproduces the reference presence footprint exactly.*</p>
</section>
</section>
<section id="prediction-maps" class="level2">
<h2 class="anchored" data-anchor-id="prediction-maps">Prediction maps</h2>
<section id="single-species-benchmark-predictions" class="level3">
<h3 class="anchored" data-anchor-id="single-species-benchmark-predictions">Single-species benchmark predictions</h3>
<p><img src="images/existing_benchmark_maps.png" class="img-fluid"></p>
<p><em>Bradypus (South America): Maxent, Bioclim, GLM, RF. Anguilla BRT is on a fabricated one-cell-per-site grid (scattered pixels), so its “map” is not geographically meaningful — only its per-site predictions are.</em></p>
</section>
<section id="nsw14-valavi-continuous-surface-published-points-agreement" class="level3">
<h3 class="anchored" data-anchor-id="nsw14-valavi-continuous-surface-published-points-agreement">nsw14 (Valavi) — continuous surface, published points &amp; agreement</h3>
<p>The clearest check places each algorithm in one row across <strong>three columns</strong>: (1) our continuous re-fit of Valavi’s config predicted across the whole NSW grid, (2) Valavi et al.&nbsp;(2021)’s own published point predictions (<code>Models_prediction/*.csv</code>) at the 702 evaluation sites, and (3) the site-level agreement — our raster value at each site (y) against Valavi’s published value (x), with the 1:1 line and per-model Pearson <em>r</em>. Columns 1–2 share the same 0–1 suitability scale; red rings mark observed presences.</p>
<p><img src="images/valavi_nsw14_paired_continuous_vs_points.png" class="img-fluid"></p>
<p><em>For every algorithm the published points fall on our continuous surface — same eastern escarpment / north-east coast hotspot, same magnitude — and the agreement column makes it quantitative: GLM/GAM/MaxEnt/BRT collapse onto the 1:1 line (<strong>r = 1.000</strong>), MARS <strong>0.998</strong>, RF <strong>0.992</strong> (small stochastic scatter). The points are Valavi’s actual published values (<code>disPa</code> coordinates over the NSW border), not our reproduction, so this comparison is independent of our package-version environment. This is the per-model view of the 702-site table below.</em></p>
<p><strong>These maps reproduce Valavi’s published predictions.</strong> Extracting each raster band at Valavi’s 702 evaluation sites and correlating with the original <code>Models_prediction/*.csv</code>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>model</th>
<th>Pearson</th>
<th>Spearman</th>
<th>match</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GLM</td>
<td>1.0000</td>
<td>1.0000</td>
<td><strong>exact</strong></td>
</tr>
<tr class="even">
<td>GAM</td>
<td>1.0000</td>
<td>1.0000</td>
<td><strong>exact</strong></td>
</tr>
<tr class="odd">
<td>MaxEnt</td>
<td>1.0000</td>
<td>1.0000</td>
<td><strong>exact</strong></td>
</tr>
<tr class="even">
<td>BRT</td>
<td>1.0000</td>
<td>1.0000</td>
<td><strong>exact</strong></td>
</tr>
<tr class="odd">
<td>MARS</td>
<td>0.9976</td>
<td>0.9980</td>
<td>near-perfect</td>
</tr>
<tr class="even">
<td>RF</td>
<td>0.9922</td>
<td>0.9296</td>
<td>high (RF vote-fraction ties lower Spearman)</td>
</tr>
</tbody>
</table>
<p>This works because <code>disEnv</code> — the environmental values Valavi predicted their points on — is itself sampled from these NSW rasters, so the raster value at each site <em>is</em> the value Valavi used. GLM, GAM, MaxEnt and BRT reproduce it exactly; MARS/RF show only small stochastic / version scatter (RF’s vote-fraction ties lower its Spearman). The agreement column of the figure above is the per-model, Pearson view of this table.</p>
</section>
</section>
<section id="agreement-analysis" class="level2">
<h2 class="anchored" data-anchor-id="agreement-analysis">Agreement analysis</h2>
<section id="ecocommons-vs-benchmark-every-test" class="level3">
<h3 class="anchored" data-anchor-id="ecocommons-vs-benchmark-every-test">EcoCommons vs benchmark — every test</h3>
<p><img src="images/ec_vs_benchmarks_all.png" class="img-fluid"></p>
<p><em>Single-species tests (Bradypus / Anguilla) and nsw14 vs Valavi, grouped by algorithm. After aligning weighting (BRT + MARS + GAM) and turning rescaling off (RF/GLM), <strong>all eleven panels sit on the 1:1 line</strong> — magnitude </em>and* ranking agree across the board.*</p>
<p><img src="images/ec_vs_benchmarks_geo.png" class="img-fluid"></p>
<p><em>The five geographic (spatial-only) models (tests 12–16), EcoCommons projection (y) vs the <code>dismo</code> reference on identical inputs (x). Continuous models (GeoDist, GeoIDW) collapse onto the 1:1 line (<strong>Pearson r = 1.000</strong>); the binary models (Convex Hull, Circles, Voronoi Hull) match cell-for-cell (<strong>agreement = 1.000</strong>, jittered so the 0/0 and 1/1 clusters are visible). Circles is shown after its fix. Every geographic model is an exact match to its <code>dismo</code> reference.</em></p>
</section>
</section>
<section id="reproducibility-benchmark-provenance" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility-benchmark-provenance">Reproducibility &amp; benchmark provenance</h2>
<p>The single most important thing to understand about these <code>nsw14</code> benchmarks is <strong>what they are a reference <em>to</em></strong> — because it determines when they must be regenerated and what “still matching Valavi” actually means.</p>
<section id="two-different-reference-points" class="level3">
<h3 class="anchored" data-anchor-id="two-different-reference-points">Two different reference points</h3>
<p>There are two distinct notions of “matching a reference”, and they behave very differently:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Independent reimplementation</strong> (what the <code>.tif</code> benchmarks are)</th>
<th><strong>Published paper numbers</strong> (Valavi’s <code>Models_prediction/*.csv</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Produced by</td>
<td><code>generate_nsw14_valavi_benchmarks.R</code> — Valavi’s <em>exact configs</em> re-run through the algorithm’s own R package (<code>gam</code>, <code>randomForest</code>, <code>earth</code>, <code>dismo::maxent</code>, <code>dismo::gbm.step</code>)</td>
<td>Valavi et al.&nbsp;(2021), fixed external artifact</td>
</tr>
<tr class="even">
<td>What the test checks</td>
<td><strong>Implementation fidelity</strong> — does EcoCommons wire up the algorithm the same way an independent implementation does?</td>
<td><strong>Literature agreement</strong> — do we reproduce the actual published predictions?</td>
</tr>
<tr class="odd">
<td>Metric used here</td>
<td><strong>Pearson</strong> on absolute suitability (the agreement tables above)</td>
<td><strong>Pearson/Spearman</strong> at the 702 evaluation sites (the “reproduce Valavi’s published predictions” table above)</td>
</tr>
<tr class="even">
<td>Sensitive to package version?</td>
<td><strong>Cancels out</strong> — see below</td>
<td><strong>Yes</strong> — this is the real anchor to the paper</td>
</tr>
</tbody>
</table>
<p>The <code>.tif</code> benchmarks are <strong>not frozen EcoCommons snapshots</strong> (they come from different engines) and <strong>not</strong> Valavi’s literal published rasters either. They are a faithful <em>re-run of Valavi’s recipe</em>. So “matching the paper” via these benchmarks means “matching a faithful reproduction of Valavi’s config”, not bit-matching the 2021 output.</p>
</section>
<section id="what-changes-the-final-benchmark" class="level3">
<h3 class="anchored" data-anchor-id="what-changes-the-final-benchmark">What changes the final benchmark</h3>
<p>The absolute suitability values written into each benchmark <code>.tif</code> depend on the <strong>software environment they were generated in</strong> — not just the algorithm and config. In order of impact:</p>
<ol type="1">
<li><strong>Package version drift.</strong> Tree-ensemble learners are the main offender: <strong><code>gbm</code> (BRT)</strong> absolute predicted probabilities shift across <code>gbm</code> versions / platforms. <code>randomForest</code>, <code>earth</code>, <code>gam</code>, <code>maxent.jar</code> are far more stable. This is the reproducibility issue that forced the BRT benchmark to be regenerated inside the CI container rather than frozen from a dev machine (newer <code>gbm</code> on macOS drifts on Pearson in CI).</li>
<li><strong>The R version and compiler toolchain</strong> (numerical libraries, BLAS).</li>
<li><strong>Config / weighting changes</strong> — e.g.&nbsp;background down-weighting, normalisation, hyper-parameters. BRT down-weighting is now applied through the <strong>supported <code>site_weight_scheme = "downweight"</code> option</strong> in the <code>nsw14_brt</code> spec (no longer a test-only mock), so EcoCommons matches Valavi’s config directly.</li>
<li><strong>The training-point construction</strong> — dedup one-per-cell, complete-cases filtering — which is deliberately matched to EcoCommons’ <code>filter.raster</code>.</li>
</ol>
<p>Because of (1)–(2), <strong>benchmarks must be regenerated in the pinned CI container</strong> (<code>ec-rpkg-ci-test-env</code>), never on a local dev machine. Locally, R is not <code>renv</code>-activated, so a laptop pulls whatever package versions it happens to have — reintroducing exactly the drift the CI-native benchmark exists to avoid.</p>
</section>
<section id="why-regenerating-in-the-same-environment-is-safe" class="level3">
<h3 class="anchored" data-anchor-id="why-regenerating-in-the-same-environment-is-safe">Why regenerating in the same environment is safe</h3>
<p>When a benchmark is regenerated in a bumped environment, <strong>both</strong> the benchmark <em>and</em> EcoCommons run through the <em>same</em> new engine (for BRT, the same new <code>gbm</code>). Their absolute values shift <strong>together</strong>, so their <strong>Pearson agreement is preserved</strong>. That is precisely why regenerating-in-CI works: it cancels version drift on both sides.</p>
<p>The blind spot: because the two sides move together, a genuine engine change could move <strong>both</strong> the benchmark and EcoCommons away from Valavi’s <em>2021</em> numbers while they still agree with each other. The guard against silently re-baselining away from the paper is twofold:</p>
<ul>
<li><strong>Rank-drift check (in the generator).</strong> <code>write_bench()</code> reports the <strong>Spearman</strong> correlation between each newly generated prediction and the currently committed <code>.tif</code>, and warns if it drops below <code>0.98</code>. Benign scale drift (a new <code>gbm</code>) leaves rank order intact (Spearman ≈ 1); a low Spearman means the <em>science</em> moved, not just the scale — investigate before committing.</li>
<li><strong>Literature anchor.</strong> The “reproduce Valavi’s published predictions” table (702-site Pearson/Spearman vs the original CSVs) is the check that actually ties us to the paper, and it is version-robust because it is rank-friendly.</li>
</ul>
<p><strong>Rule of thumb:</strong> benchmark-generation environment == test-execution environment == the pinned container image. Whenever that pin moves (a package patch or a base-image rebuild), regenerate the affected <code>.tif</code> benchmarks <em>in the new environment</em> and commit them alongside the version bump — after confirming the rank-drift guard stays green.</p>
</section>
<section id="reproducibility-environment-pinned-package-versions" class="level3">
<h3 class="anchored" data-anchor-id="reproducibility-environment-pinned-package-versions">Reproducibility environment — pinned package versions</h3>
<p>These are the versions the benchmarks and agreement tests are pinned to, from <code>renv-main.lock</code> (== the deployed base image <code>ec-base-r4.2</code> / CI test image <code>ec-rpkg-ci-test-env</code>). The base image is rebuilt only via a manual pipeline (<code>BUILD_BASE=1</code>); <code>renv</code> is not auto-activated, so this lock governs the container, not ad-hoc local runs.</p>
<p><strong>R 4.2.2</strong> · CRAN snapshot <code>https://cloud.r-project.org</code></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Version</th>
<th>Role in the agreement suite</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>biomod2</code></td>
<td>4.2-2</td>
<td>EcoCommons GLM / RF / MARS engine (wraps the learners below)</td>
</tr>
<tr class="even">
<td><code>dismo</code></td>
<td>1.3-9</td>
<td>EcoCommons BRT (<code>gbm.step</code>), MaxEnt (<code>maxent.jar</code>), Bioclim</td>
</tr>
<tr class="odd">
<td><code>gbm</code></td>
<td>2.1.8.1</td>
<td>BRT learner — <strong>version-sensitive</strong>; drives CI-native regeneration</td>
</tr>
<tr class="even">
<td><code>randomForest</code></td>
<td>4.7-1.1</td>
<td>RF learner + Valavi RF benchmark</td>
</tr>
<tr class="odd">
<td><code>earth</code></td>
<td>5.3.2</td>
<td>MARS learner + Valavi MARS benchmark</td>
</tr>
<tr class="even">
<td><code>terra</code></td>
<td>1.7-3</td>
<td>Raster I/O, benchmark grid, cell dedup</td>
</tr>
<tr class="odd">
<td><code>raster</code></td>
<td>3.6-14</td>
<td><code>dismo</code>/<code>raster</code>-style stacks for geographic models</td>
</tr>
<tr class="even">
<td><code>sf</code></td>
<td>1.0-9</td>
<td>Vector geometry / constraint regions</td>
</tr>
<tr class="odd">
<td><code>caret</code></td>
<td>6.0-93</td>
<td>Valavi’s original Appendix S2 MARS tuning (continuous maps)</td>
</tr>
<tr class="even">
<td><code>testthat</code></td>
<td>3.1.6</td>
<td>Test runner (pinned; avoid newer-only features in CI)</td>
</tr>
</tbody>
</table>
<p><em>Generation-only, <strong>not</strong> pinned in the lock:</em> <code>gam::step.Gam</code> (GLM benchmark), <code>mgcv::gam</code> (GAM benchmark) and <code>rJava</code> (MaxEnt/JVM) are installed on top of the base image rather than via <code>renv</code>, so they take whatever the CI image provides at generation time. <code>gam</code> / <code>mgcv</code> are used only to build the GLM / GAM <code>.tif</code> benchmarks, not by the EcoCommons runtime.</p>
</section>
</section>
<section id="crossr-version-reproducibility-the-four-not-yet-tested-biomod2-learners-sre-fda-ann-gbm" class="level2">
<h2 class="anchored" data-anchor-id="crossr-version-reproducibility-the-four-not-yet-tested-biomod2-learners-sre-fda-ann-gbm">Cross–R-version reproducibility: the four “not-yet-tested” <code>biomod2</code> learners (SRE · FDA · ANN · GBM)</h2>
<p>The algorithm-coverage table above lists <strong>SRE, FDA, ANN and GBM</strong> as <em>not yet</em> guarded by a scientific-agreement test. As a first step toward covering them — and as a controlled study of <em>what actually breaks reproducibility</em> — we reproduced all four exactly as taught in Guisan, Thuiller &amp; Zimmermann’s <em>Habitat Suitability and Distribution Models</em> (2017; the public <code>hsdm</code> companion code), then re-ran each one under the book’s <strong>original 2017 software</strong> and under a <strong>current</strong> stack, and diffed the predictions cell-by-cell.</p>
<p><strong>Setup.</strong> Species <em>Vulpes vulpes</em> (red fox); the book’s <code>mammals_and_bioclim_table</code> (8,542 global grid cells, 4,203 presences / 4,339 absences at 1.5°); four predictors <code>bio3, bio7, bio11, bio12</code>. Model calls are the book’s verbatim configurations (<code>biomod2::sre</code>; <code>mda::fda(method = mars)</code>; <code>nnet</code>, size 6 / decay 0.001; <code>gbm</code>, bernoulli / 10 000 trees / depth 3 / shrinkage 0.01 / 10-fold CV), same <code>set.seed(555)</code>. The “old” environment is a pinned Docker image; the “new” one is current CRAN.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th>Old environment (Docker)</th>
<th>Current environment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R</td>
<td><strong>3.4.1</strong> (2017-06-30)</td>
<td>4.5.0 (2025)</td>
</tr>
<tr class="even">
<td>SRE</td>
<td>biomod2 <strong>3.3-7</strong> <code>sre()</code> verbatim</td>
<td>biomod2 4.2-2 <code>bm_SRE</code></td>
</tr>
<tr class="odd">
<td>FDA</td>
<td><strong>mda 0.4-9</strong></td>
<td>mda 0.5-5</td>
</tr>
<tr class="even">
<td>ANN</td>
<td><strong>nnet 7.3-12</strong></td>
<td>nnet 7.3-20</td>
</tr>
<tr class="odd">
<td>GBM</td>
<td><strong>gbm 2.1.3</strong></td>
<td>gbm 2.2.3</td>
</tr>
</tbody>
</table>
<p><strong>Result — reproducibility tracks determinism.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th>Nature</th>
<th>Cross-version agreement</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SRE</td>
<td>deterministic envelope</td>
<td>100% cells identical</td>
<td><strong>exact</strong></td>
</tr>
<tr class="even">
<td>FDA</td>
<td>deterministic (MARS)</td>
<td>Pearson <strong>1.0000</strong></td>
<td><strong>exact</strong></td>
</tr>
<tr class="odd">
<td>ANN — single fit</td>
<td>stochastic (random init)</td>
<td>Pearson <strong>0.945</strong></td>
<td>diverges</td>
</tr>
<tr class="even">
<td>ANN — 15× ensemble</td>
<td>stochastic, averaged</td>
<td>Pearson <strong>0.997</strong></td>
<td>largely fixed</td>
</tr>
<tr class="odd">
<td>GBM</td>
<td>stochastic (bagging + CV)</td>
<td>Pearson <strong>0.9997</strong></td>
<td>near-identical</td>
</tr>
</tbody>
</table>
<p><img src="images/hsdm_xversion_agreement.png" class="img-fluid"></p>
<p><em>Each row is one model: predicted suitability under R 3.4.1 (left) vs R 4.5.0 (middle) — sharing a suitability scale, with observed occurrences as rings (red = presence, grey = absence) — and the agreement scatter (right): old (x) vs new (y), dashed 1:1 line, Pearson r, dots coloured by observed status. SRE and FDA reproduce to the bit; a single ANN drifts into a “leaf”-shaped cloud; averaging 15 ANN fits pulls it back onto the diagonal; GBM barely moves. Styling matches the paired figures above.</em></p>
<p><strong>Why does ANN diverge — didn’t we hold the configuration fixed?</strong> We did: identical data, hyper-parameters and seed produced <em>bit-identical initial weights</em> in both versions. A 2×2 experiment crossing the R build with the <code>nnet</code> version isolates the cause:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Only thing that differs</th>
<th>Pearson r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>same R 3.4.1; <code>nnet</code> 7.3-12 → 7.3-20</td>
<td>package source</td>
<td><strong>1.000000 (bit-identical)</strong></td>
</tr>
<tr class="even">
<td>same <code>nnet</code> 7.3-20; R 3.4.1 → 4.6.1 (both Linux / gcc)</td>
<td>R build</td>
<td>0.940</td>
</tr>
<tr class="odd">
<td>same <code>nnet</code> 7.3-20 / R 4.x; Linux·gcc → macOS·clang·arm64</td>
<td>compiler + CPU</td>
<td>0.951</td>
</tr>
</tbody>
</table>
<p>The <code>nnet</code> <em>package version</em> is <strong>not</strong> the cause (bit-identical). The divergence comes from the <strong>compiled floating-point environment</strong> — R build, C compiler, CPU architecture (FMA), and the system <code>libm</code> (<code>exp</code>/<code>log</code> inside the logistic output units) each perturb the arithmetic at the ~10⁻¹⁵ level. Because <code>nnet</code> minimises a <strong>non-convex</strong> loss by BFGS and never reaches a unique optimum, those perturbations <strong>compound into different local minima</strong> (final loss 565 vs 572 from the identical start). The <em>magnitude</em> of the disagreement follows the Bernoulli variance <code>p(1−p)</code> — the derivative of the logistic output — peaking at suitability ≈ 0.5 and vanishing at the saturated extremes, which is exactly the “leaf” shape.</p>
<p><img src="images/hsdm_ann_leaf.png" class="img-fluid"></p>
<p><em>ANN cross-version scatter (the “leaf”) and mean disagreement by suitability band; disagreement is ~13× larger near p = 0.5 than at 0/1, tracking p(1−p).</em></p>
<p><strong>This is the same reproducibility story the benchmark-provenance section tells, pushed to its logical end.</strong> There, tree-ensembles (<code>gbm</code>) drift across versions while <code>randomForest</code> / <code>earth</code> / <code>maxent.jar</code> stay stable; here, an <em>unaveraged</em> neural network is the least reproducible learner of the four, and the two mitigations are precisely the ones already in use on the platform:</p>
<ol type="1">
<li><strong>Pin the environment.</strong> A fixed container makes the result bit-identical — confirmed by the old <code>biomod2 3.3-7</code> <code>sre()</code> matching the modern <code>bm_SRE</code> on <strong>8,542 / 8,542</strong> cells, and by re-running the <em>same</em> <code>nnet</code> source in the <em>same</em> image (r = 1.000000).</li>
<li><strong>Ensemble.</strong> Averaging 15 ANN fits recovers <strong>r = 0.997</strong> without pinning anything — which is why GBM, an ensemble by construction, barely drifts.</li>
</ol>
<p>SRE and FDA need neither: a single deterministic quantity has one answer in any environment. The full reproduction (verbatim code, performance, prediction/response-curve figures) and the Docker harness live in the <code>hsdm</code> companion repository.</p>
</section>
<section id="methods-metrics-for-reproduction-performance" class="level2">
<h2 class="anchored" data-anchor-id="methods-metrics-for-reproduction-performance">Methods — metrics for reproduction performance</h2>
<p>Every agreement test runs a real EcoCommons projection and compares it, <strong>cell by cell over the prediction grid</strong>, against an independent benchmark (for the HSDM suite, our verbatim reproduction of the book). We score the two rasters with two complementary correlation metrics, and read the <em>shape</em> of their scatter to diagnose <em>how</em> they (dis)agree.</p>
<section id="two-metrics" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="two-metrics">Two metrics</h3>
<ul>
<li><strong>Pearson correlation</strong> — agreement on the <strong>absolute</strong> predicted values. It reaches 1.0 only if the two surfaces are related by a straight line, so it penalises any difference in scale or probability calibration. This is the strict headline metric, used where both engines are on the same 0–1 scale (as on the balanced HSDM <em>Vulpes</em> data).</li>
<li><strong>Spearman rank correlation</strong> — agreement on the <strong>ordering</strong> of cells. It reaches 1.0 whenever the two surfaces rank every cell the same way, <em>regardless of the value scale</em>; it is invariant to any monotonic transform (rescaling, a different sigmoid/posterior calibration, etc.).</li>
</ul>
<p><strong>Why both.</strong> For an SDM the ecologically meaningful quantity is usually the <strong>ranking</strong> of suitability — which places are more suitable, where a threshold falls — not the absolute probability scale. So a high Spearman with a lower Pearson means <em>“same science, different scale”</em>: a benign recalibration, not a scientific disagreement. We report Pearson where the scales match and lean on Spearman when a monotonic scale difference would otherwise understate an exact match.</p>
</section>
<section id="reading-the-agreement-scatter" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="reading-the-agreement-scatter">Reading the agreement scatter</h3>
<p>Plotting benchmark (x) against EcoCommons (y) makes the <em>kind</em> of agreement visible:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Scatter shape</th>
<th>Meaning</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Straight line on the 1:1 diagonal</strong></td>
<td>exact agreement (Pearson ≈ Spearman ≈ 1)</td>
<td>SRE</td>
</tr>
<tr class="even">
<td><strong>Clean S-curve, no scatter</strong></td>
<td><em>deterministic</em> monotonic rescaling — identical ranking (Spearman = 1), slightly different value scale; benign</td>
<td>FDA (r_s = 1.000, r = 0.999)</td>
</tr>
<tr class="odd">
<td><strong>Lens / “almond” cloud</strong></td>
<td><em>stochastic</em> disagreement — genuine run-to-run noise, widest in the uncertain mid-range (~0.5) and pinched where predictions saturate (0/1), tracking <em>p(1 − p)</em></td>
<td>GBM (thin), ANN (fat)</td>
</tr>
</tbody>
</table>
<p>The S-curve and the almond are two faces of the same sigmoid output transform: the S is its noiseless skeleton (a pure rescaling), the almond is that skeleton smeared by stochastic noise. A <strong>fat</strong> almond means large noise (a single ANN’s random weight initialisation → different local minima); GBM’s per-tree bagging almond is by contrast <strong>negligible</strong> — averaged over 10,000 trees, almost nothing survives — so once its config is matched GBM’s scatter is essentially a straight line.</p>
</section>
<section id="deterministic-vs-stochastic-learners" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="deterministic-vs-stochastic-learners">Deterministic vs stochastic learners</h3>
<p>This taxonomy sets the achievable ceiling:</p>
<ul>
<li><strong>Deterministic</strong> — <strong>SRE</strong> (quantile envelope) and <strong>FDA</strong> (MARS) compute a single fixed answer, so any correct implementation reproduces them to Pearson/Spearman ≈ 1 (FDA’s tiny S is a rank-preserving wrapper hairline, not a disagreement).</li>
<li><strong>Stochastic</strong> — <strong>GBM</strong> (bagging) and <strong>ANN</strong> (random weight init) carry irreducible noise, but they land in very different places. <strong>GBM reproduces to ~0.999 with a single fit</strong> <em>once its config is matched</em>: its per-tree bagging noise is already averaged away by the 10,000-tree ensemble, so almost nothing survives. (Its earlier 0.955 was a <em>config mismatch</em> — the benchmark used the book’s GBM settings while EcoCommons fell back to biomod2’s defaults — not bagging noise; pinning the config fixes it.) A <strong>single</strong> ANN fit is the opposite: it does <em>no</em> internal averaging, so it lands in a different local minimum every time and reproduces only to ~0.81 — which is why we test ANN as a <strong>50× ensemble</strong> (→ 0.996). The general rule: <em>averaging turns a non-reproducible stochastic learner into a reproducible one</em> — GBM does it internally (10k trees), we do it explicitly for ANN (50 nets).</li>
</ul>
<p>Per-algorithm pass thresholds reflect this: <strong>0.99</strong> for SRE, FDA and GBM, and <strong>0.95</strong> for the ANN ensemble.</p>
</section>
</section>
<section id="ecocommons-agreement-on-the-hsdm-data-sre-fda-ann-gbm" class="level2">
<h2 class="anchored" data-anchor-id="ecocommons-agreement-on-the-hsdm-data-sre-fda-ann-gbm">EcoCommons agreement on the HSDM data (SRE · FDA · ANN · GBM)</h2>
<p>The cross-version work above validates the <em>reference</em> implementation. The final step closes the loop: does <strong>EcoCommons itself</strong> reproduce that reference? We converted the book’s <em>Vulpes vulpes</em> data into EcoCommons input fixtures (4,203 presences / 4,339 absences on the 1.5° global grid, with <code>bio3/bio7/bio11/bio12</code>), ran EcoCommons’ own SRE / FDA / ANN / GBM, and scored each projection against <strong>our verbatim reproduction of Guisan, Thuiller &amp; Zimmermann (2017)</strong> — i.e.&nbsp;the benchmark is <em>the projection we made</em>, not a frozen EcoCommons snapshot. These are now <code>testthat</code> agreement tests in the EcoCommons R package (<code>test-sdm_projection_agreement.R</code>, <code>hsdm_*</code> specs).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Algorithm</th>
<th>Engine</th>
<th>Nature</th>
<th>Pearson</th>
<th>Spearman</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SRE</strong></td>
<td><code>biomod2</code> (envelope)</td>
<td>deterministic</td>
<td><strong>1.000</strong></td>
<td><strong>1.000</strong></td>
<td>✅ exact</td>
</tr>
<tr class="even">
<td><strong>FDA</strong></td>
<td><code>mda</code> (MARS)</td>
<td>deterministic</td>
<td><strong>0.999</strong></td>
<td><strong>1.000</strong></td>
<td>✅ exact</td>
</tr>
<tr class="odd">
<td><strong>GBM</strong></td>
<td><code>gbm</code></td>
<td>stochastic (bagging)</td>
<td><strong>0.999</strong></td>
<td><strong>0.999</strong></td>
<td>✅ exact</td>
</tr>
<tr class="even">
<td><strong>ANN</strong></td>
<td><code>nnet</code></td>
<td>stochastic — <strong>50× ensemble</strong> †</td>
<td><strong>0.996</strong></td>
<td><strong>0.993</strong></td>
<td>✅ reproduced</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled" title="† ANN is changed from the book — and why">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
† ANN is changed from the book — and why
</div>
</div>
<div class="callout-body-container callout-body">
<p>The book fits a <strong>single</strong> ANN. But a single neural network is not a reproducible object: its non-convex training lands in an <strong>arbitrary local minimum</strong> set by the random starting weights, and across seeds the model quality swings wildly (<strong>AUC 0.73–0.97 on this data</strong>). Two independent implementations therefore never match — the book’s ANN and EcoCommons’ ANN agree only at <strong>Pearson ≈ 0.81</strong>, and neither is even reproducible run-to-run.</p>
<p>So for ANN we deliberately <strong>change the configuration to an ensemble</strong>: fit <strong>50 networks, each on a different random 80/20 split, and average them</strong> (EcoCommons’ native <code>nb_run_eval = 50</code>). Averaging converges to the stable <em>expected</em> prediction — a well-defined, reproducible target. The payoff: EcoCommons’ 50-net ensemble reproduces our 50-net ensemble at <strong>Pearson 0.996</strong>, and the EcoCommons ensemble is itself reproducible run-to-run at <strong>0.999</strong> (a single fit was neither). This is a strictly <em>better</em> model than the book’s single fit, and it moves ANN from “the fragile outlier” into the reproducible column. <em>You cannot reproduce one coin flip; you can reproduce the average of 50.</em></p>
</div>
</div>
<p><img src="images/ec_hsdm_vulpes_agreement.png" class="img-fluid"></p>
<p><em>Each row is one algorithm: our HSDM reproduction (left) vs the EcoCommons projection (middle), over the global</em> Vulpes vulpes <em>range, and the site-level agreement (right) — our value at each cell (x) against EcoCommons’ (y), with the 1:1 line and Pearson r. All four scatters collapse onto the 1:1 line and the map columns are visually indistinguishable. On the balanced Vulpes presence/absence with the book’s verbatim configuration both engines sit on the same 0–1 scale, so Pearson (not just rank) is high. <strong>ANN is the 50× ensemble</strong> (changed from the book — see the note above): a single ANN fit would open into a noisy cloud (Pearson ≈ 0.81, an arbitrary local minimum), but averaging 50 fits converges to a stable, reproducible surface that EcoCommons reproduces to Pearson 0.996.</em></p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><strong>Booth, T.H., Nix, H.A., Busby, J.R. &amp; Hutchinson, M.F. (2014).</strong> BIOCLIM: the first species distribution modelling package, its early applications and relevance to most current MaxEnt studies. <em>Diversity and Distributions</em> 20: 1–9.</li>
<li><strong>Guisan, A., Thuiller, W. &amp; Zimmermann, N.E. (2017).</strong> <em>Habitat Suitability and Distribution Models: With Applications in R.</em> Cambridge University Press. (SRE / FDA / ANN / GBM reproduction and the cross–R-version experiment; companion <code>hsdm</code> code.)</li>
<li><strong>Breiman, L. (2001).</strong> Random forests. <em>Machine Learning</em> 45: 5–32.</li>
<li><strong>Elith, J., Leathwick, J.R. &amp; Hastie, T. (2008).</strong> A working guide to boosted regression trees. <em>Journal of Animal Ecology</em> 77: 802–813.</li>
<li><strong>Elith, J., Graham, C.H., Valavi, R., Abegg, M., Bruce, C., Ford, A., Guisan, A., Hijmans, R.J., Huettmann, F., Lohmann, L.G., Loiselle, B.A., Moritz, C., Overton, J.McC., Peterson, A.T., Phillips, S., Richardson, K., Williams, S., Wiser, S.K., Wohlgemuth, T. &amp; Zimmermann, N.E. (2020).</strong> Presence-only and presence-absence data for comparing species distribution modeling methods. <em>Biodiversity Informatics</em> 15: 69–80. (NCEAS data; distributed via the <code>disdat</code> R package and OSF project <code>kwc4v</code>.)</li>
<li><strong>Friedman, J.H. (1991).</strong> Multivariate adaptive regression splines. <em>The Annals of Statistics</em> 19: 1–67.</li>
<li><strong>Hastie, T.J. &amp; Tibshirani, R.J. (1990).</strong> <em>Generalized Additive Models.</em> Chapman &amp; Hall. (<code>gam::step.Gam</code> stepwise selection.)</li>
<li><strong>Hijmans, R.J., Phillips, S., Leathwick, J. &amp; Elith, J.</strong> <code>dismo</code>: Species Distribution Modeling. R package. (<code>gbm.step</code>, <code>maxent</code>, <code>bioclim</code>.)</li>
<li><strong>Hijmans, R.J. &amp; Elith, J.</strong> <em>Species distribution modeling with R.</em> (The <code>dismo</code> package vignette; Chapter 13 “Geographic models” — <code>geoDist</code>, <code>convHull</code>, <code>circles</code>, <code>geoIDW</code>, <code>voronoiHull</code>.)</li>
<li><strong>McCullagh, P. &amp; Nelder, J.A. (1989).</strong> <em>Generalized Linear Models</em>, 2nd edn. Chapman &amp; Hall.</li>
<li><strong>Nix, H.A. (1986).</strong> A biogeographic analysis of Australian elapid snakes. In: <em>Atlas of Elapid Snakes of Australia</em> (ed.&nbsp;R. Longmore), pp.&nbsp;4–15. Australian Government Publishing Service.</li>
<li><strong>Phillips, S.J., Anderson, R.P. &amp; Schapire, R.E. (2006).</strong> Maximum entropy modeling of species geographic distributions. <em>Ecological Modelling</em> 190: 231–259.</li>
<li><strong>Phillips, S.J. &amp; Dudík, M. (2008).</strong> Modeling of species distributions with Maxent: new extensions and a comprehensive evaluation. <em>Ecography</em> 31: 161–175.</li>
<li><strong>Thuiller, W., Lafourcade, B., Engler, R. &amp; Araújo, M.B. (2009).</strong> BIOMOD – a platform for ensemble forecasting of species distributions. <em>Ecography</em> 32: 369–373. (<code>biomod2</code> R package.)</li>
<li><strong>Valavi, R., Guillera-Arroita, G., Lahoz-Monfort, J.J. &amp; Elith, J. (2021).</strong> Predictive performance of presence-only species distribution models: a benchmark study with reproducible code. <em>Ecological Monographs</em> 92(1): e01486. (Appendix S1/S2 configurations; <code>Models_prediction</code> per-species outputs.)</li>
<li><strong>Wood, S.N. (2017).</strong> <em>Generalized Additive Models: An Introduction with R</em>, 2nd edn. Chapman &amp; Hall/CRC. (<code>mgcv</code> package; GAM benchmark engine.)</li>
</ul>


</section>
</section>

</main> <!-- /main -->



<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>footer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="footer_files/libs/clipboard/clipboard.min.js"></script>
<script src="footer_files/libs/quarto-html/quarto.js"></script>
<script src="footer_files/libs/quarto-html/popper.min.js"></script>
<script src="footer_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="footer_files/libs/quarto-html/anchor.min.js"></script>
<link href="footer_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="footer_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="footer_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="footer_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="footer_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">






<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div style="text-align: center;">
<p><img src="https://raw.githubusercontent.com/EcoCommons-Australia-2024-2026/ec-notebook_site_materials/main/images/EC_section_break.png" alt="Section Break" width="750"></p>
</div>
<div style="max-width: 1000px; margin: 45; text-align: center; padding: 10px;">
<p>
EcoCommons received investment (<a href="https://doi.org/10.3565/chbq-mr75">https://doi.org/10.3565/chbq-mr75</a>) from the Australian Research Data Commons (ARDC). The ARDC is enabled by the National Collaborative Research Infrastructure Strategy (NCRIS).
</p>
<div style="text-align: center;">
<h3 class="no-anchor" style="text-align: center;">
<p>Our Partner</p>
</h3>
</div>
<div style="text-align: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/EcoCommons-Australia-2024-2026/ec-notebook_site_materials/main/images/updated_ourpartner_2025.png" class="img-fluid figure-img"></p>
<figcaption> </figcaption>
</figure>
</div>
</div>
<h3 class="no-anchor" style="text-align: center;">
<p>How to Cite EcoCommons</p>
</h3>
<p style="text-align: center;">
</p><p>If you use EcoCommons in your research, please cite the platform as follows:</p>
<p></p>
<blockquote style="text-align: center;" class="blockquote">
<p>EcoCommons Australia 2026. <em>EcoCommons Australia – a collaborative commons for ecological and environmental modelling</em>, Queensland Cyber Infrastructure Foundation, Brisbane, Queensland. Available at: <a href="https://data–explorer.app.ecocommons.org.au/">https://data–explorer.app.ecocommons.org.au/</a> (Accessed: MM DD, YYYY). <a href="https://doi.org/10.3565/chbq-mr75">https://doi.org/10.3565/chbq-mr75</a></p>
</blockquote>
<p style="text-align: center;">
</p><p>You can download the citation file for EcoCommons Australia here: <a href="reference.bib">Download the BibTeX file</a></p>
<p></p>
<p style="text-align: center;">
</p><p>© 2026 EcoCommons. All rights reserved.</p>
<p></p>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->





<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ecocommonsaustralia\.github\.io\/notebook-blog");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>