---
title: "Data Preparation Overview"
format:
  html:
    toc: true
---

# Data Preparation Overview

Welcome to the Data Preparation section! Here, you can find various guides and resources to help you with the preparation of data for Species Distribution Models (SDM).

## Available Guides

Below is a list of specific topics related to data preparation. Click on each link to access more detailed guides.

### 1. Environmental Data Preparation

[Environmental Data Preparation](data_prep/raster_preparation.qmd)\
This guide will help you prepare environmental variables such as bioclimatic data, land use, and others required for SDM.

### 2. Imbalanced dataset Part 1 and 2

[Imbalanced dataset Part 1](data_prep/imbalanced_data_part1.qmd)\
[Imbalanced dataset Part 2](data_prep/imbalanced_data_part2.qmd)\
Learn how to deal with the issue of imbalanced dataset.

### 3. Raster Processing

[Raster Processing](data_prep/raster_processing.qmd)\
Step-by-step instructions on how to handle raster data, including reprojecting, cropping, and masking.

### 4. Data Cleaning Techniques

[Data Cleaning Techniques](data_prep/data_cleaning.qmd)\
A guide on the best practices for cleaning both environmental and occurrence datasets.

------------------------------------------------------------------------

If you have questions or suggestions, please [contact the EcoCommons](mailto:support@ecocommons.org.au) team.
